# shared configurations 
version: '3'
services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
      
volumes:
  mongo-db:
