# shared configurations 
version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  nodeapp:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo  # starts container only after mongo container is started
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
