version: '3'
services:
  nodeapp:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env